### ISSUE TITLE
Issue while loading resource packs

### ISSUE THREAD

**Issue by zml2008** [Digifox03/variedMobs#4]
Been getting this error repeated in my client log when loading the [LGBeeT](https://www.curseforge.com/minecraft/texture-packs/lg-bee-t-resource-pack) resource pack. I have a few other resource packs installed, but it's not triggered until the specific LGBeeT pack is activated. This is on 1.16.2. [Full log](https://files.stellardrift.ca/mc/vmt-log-1.16.2.txt)

```
[15:09:11] [Worker-Main-12/INFO]: [STDERR]: kotlin.KotlinNullPointerException
[15:09:11] [Worker-Main-12/INFO]: [STDERR]: 	at it.digifox03.variedmobs.core.IdentifierSerializer.deserialize(IdentifierSerializer.java:45)
[15:09:11] [Worker-Main-12/INFO]: [STDERR]: 	at it.digifox03.variedmobs.core.IdentifierSerializer.deserialize(IdentifierSerializer.java:40)
[15:09:11] [Worker-Main-12/INFO]: [STDERR]: 	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
[15:09:11] [Worker-Main-12/INFO]: [STDERR]: 	at com.google.gson.Gson.fromJson(Gson.java:887)
[15:09:11] [Worker-Main-12/INFO]: [STDERR]: 	at com.google.gson.Gson.fromJson(Gson.java:952)
[15:09:11] [Worker-Main-12/INFO]: [STDERR]: 	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162)
[15:09:11] [Worker-Main-12/INFO]: [STDERR]: 	at it.digifox03.variedmobs.core.VariedSelectorSerializer.deserialize(VariedSelectorSerializer.java:27)
[15:09:11] [Worker-Main-12/INFO]: [STDERR]: 	at it.digifox03.variedmobs.core.VariedSelectorSerializer.deserialize(VariedSelectorSerializer.java:20)
[15:09:11] [Worker-Main-12/INFO]: [STDERR]: 	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
[15:09:11] [Worker-Main-12/INFO]: [STDERR]: 	at com.google.gson.Gson.fromJson(Gson.java:887)
[15:09:11] [Worker-Main-12/INFO]: [STDERR]: 	at com.google.gson.Gson.fromJson(Gson.java:852)
[15:09:11] [Worker-Main-12/INFO]: [STDERR]: 	at com.google.gson.Gson.fromJson(Gson.java:801)
[15:09:11] [Worker-Main-12/INFO]: [STDERR]: 	at com.google.gson.Gson.fromJson(Gson.java:773)
[15:09:11] [Worker-Main-12/INFO]: [STDERR]: 	at it.digifox03.variedmobs.core.ParserKt.parseSelector(ParserKt.java:53)
[15:09:11] [Worker-Main-12/INFO]: [STDERR]: 	at it.digifox03.variedmobs.core.VariedMobManager.parseVaried(VariedMobManager.java:39)
[15:09:11] [Worker-Main-12/INFO]: [STDERR]: 	at it.digifox03.variedmobs.core.VariedMobManager.access$parseVaried(VariedMobManager.java:16)
[15:09:11] [Worker-Main-12/INFO]: [STDERR]: 	at it.digifox03.variedmobs.core.VariedMobManager$prepare$1.invoke(VariedMobManager.java:45)
[15:09:11] [Worker-Main-12/INFO]: [STDERR]: 	at it.digifox03.variedmobs.core.VariedMobManager$prepare$1.invoke(VariedMobManager.java:16)
[15:09:11] [Worker-Main-12/INFO]: [STDERR]: 	at it.digifox03.variedmobs.core.VariedMobManagerKt.profiling(VariedMobManagerKt.java:14)
[15:09:11] [Worker-Main-12/INFO]: [STDERR]: 	at it.digifox03.variedmobs.core.VariedMobManager.prepare(VariedMobManager.java:41)
[15:09:11] [Worker-Main-12/INFO]: [STDERR]: 	at it.digifox03.variedmobs.core.VariedMobManager.method_18789(VariedMobManager.java:16)
[15:09:11] [Worker-Main-12/INFO]: [STDERR]: 	at net.minecraft.class_4080.method_18791(class_4080.java:11)
[15:09:11] [Worker-Main-12/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1764)
[15:09:11] [Worker-Main-12/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1756)
[15:09:11] [Worker-Main-12/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
[15:09:11] [Worker-Main-12/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016)
[15:09:11] [Worker-Main-12/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665)
[15:09:11] [Worker-Main-12/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598)
[15:09:11] [Worker-Main-12/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
```

**Comment by Digifox03** [comment]
Should be fixed by https://github.com/Digifox03/variedMobs/commit/e6f6a767f2e3a147eb7e80e4c2d6b27b62996969
