### ISSUE TITLE
Crash On Startup

### ISSUE THREAD

**Issue by Doctor-Cpu** [Digifox03/variedMobs#7]
When ever i start up minecraft only with this mod, new fabric api and fabric launcer I get this error: https://i.imgur.com/EpTDZgO.png.

Below is my game output.

`[00:02:40] [main/INFO]: Loading for game Minecraft 1.16.3
[00:02:41] [main/FATAL]: A critical error occurred
net.fabricmc.loader.discovery.ModResolutionException: Could not find required mod: varied-mobs requires {fabric-language-kotlin @ [>=1.4.0]}
	at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:169) ~[fabric-loader-0.10.0+build.208.jar:?]
	at net.fabricmc.loader.discovery.ModResolver.resolve(ModResolver.java:605) ~[fabric-loader-0.10.0+build.208.jar:?]
	at net.fabricmc.loader.FabricLoader.setup(FabricLoader.java:206) ~[fabric-loader-0.10.0+build.208.jar:?]
	at net.fabricmc.loader.FabricLoader.load(FabricLoader.java:196) [fabric-loader-0.10.0+build.208.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:127) [fabric-loader-0.10.0+build.208.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26) [fabric-loader-0.10.0+build.208.jar:?]
Caused by: net.fabricmc.loader.util.sat4j.specs.ContradictionException: Creating Empty clause ?
	at net.fabricmc.loader.util.sat4j.minisat.constraints.cnf.Clauses.propagationCheck(Clauses.java:117) ~[fabric-loader-sat4j-2.3.5.4.jar:?]
	at net.fabricmc.loader.util.sat4j.minisat.constraints.cnf.Clauses.sanityCheck(Clauses.java:97) ~[fabric-loader-sat4j-2.3.5.4.jar:?]
	at net.fabricmc.loader.util.sat4j.minisat.constraints.MixedDataStructureDanielWL.createClause(MixedDataStructureDanielWL.java:81) ~[fabric-loader-sat4j-2.3.5.4.jar:?]
	at net.fabricmc.loader.util.sat4j.minisat.core.Solver.addClause(Solver.java:401) ~[fabric-loader-sat4j-2.3.5.4.jar:?]
	at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:167) ~[fabric-loader-0.10.0+build.208.jar:?]
	... 5 more
Java HotSpot(TM) 64-Bit Server VM warning: Using incremental CMS is deprecated and will likely be removed in a future release
`

**Comment by Digifox03** [comment]
you are missing the fabric-language-kotlin mod
